### ISSUE TITLE
"socrates -g" error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [honza/honza.github.com#2]
hi.

git clone https://github.com/honza/honza.github.com
cd honza.github.com
cd _blog

root@AR:/usr/local/honza.github.com/_blog# socrates -g
it shows:
...
Saving pages...
projects.rst
resume.rst
Creating archives...
Creating pagination...
Traceback (most recent call last):
  File "/usr/local/bin/socrates", line 5, in <module>
    pkg_resources.run_script('socrates==0.9.3', 'socrates')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/EGG-INFO/scripts/socrates", line 92, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/EGG-INFO/scripts/socrates", line 52, in main
    socrates.Generator(path, options.silent)
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/socrates/socrates.py", line 129, in __init__
    self.make_pagination()
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/socrates/socrates.py", line 541, in make_pagination
    contents = self.render(self.PAGED, self._v(v))
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/socrates/socrates.py", line 160, in render
    return self.template.render(template, values)
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/socrates/renderers.py", line 33, in render
    t = self.env.get_template(template)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index_paged.html
root@AR:/usr/local/honza.github.com/_blog#

**Comment by honza** [comment]
Try `socrates -g _blog`.

**Comment by honza** [comment]
There should definitely be a better error message.

**Comment by luckypoem** [comment]
hi.

still doesn't work:
root@AR:/usr/local/honza.github.com# socrates -g _blog

it shows:
...
Saving pages...
projects.rst
resume.rst
Creating archives...
Creating pagination...
Traceback (most recent call last):
  File "/usr/local/bin/socrates", line 5, in <module>
    pkg_resources.run_script('socrates==0.9.3', 'socrates')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/EGG-INFO/scripts/socrates", line 92, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/EGG-INFO/scripts/socrates", line 52, in main
    socrates.Generator(path, options.silent)
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/socrates/socrates.py", line 129, in **init**
    self.make_pagination()
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/socrates/socrates.py", line 541, in make_pagination
    contents = self.render(self.PAGED, self._v(v))
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/socrates/socrates.py", line 160, in render
    return self.template.render(template, values)
  File "/usr/local/lib/python2.7/dist-packages/socrates-0.9.3-py2.7.egg/socrates/renderers.py", line 33, in render
    t = self.env.get_template(template)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.8-py2.7.egg/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index_paged.html
root@AR:/usr/local/honza.github.com#

and i ran "pip install jinja2" and "pip install jinja" successfully.
but the above error still happens.
